language: node_js
sudo: false
node_js:
  - "6.10.3"

# Remove wine from cache
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  ccache: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - $HOME/.pkg-cache
    - node_modules

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-6-dev

env:
  global:
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CC="clang"
    - CXX="clang++"
    - HOMEBREW_NO_AUTO_UPDATE=1
  matrix:
    - TARGET_ARCH=x64
    - TARGET_ARCH=x86

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: TARGET_ARCH=x86

os:
  - linux

before_install:
  - export HOST_OS="$TRAVIS_OS_NAME";

install:
  - ./scripts/ci/install.sh -o $HOST_OS -r $TARGET_ARCH

script:
  - ./scripts/ci/test.sh -o $HOST_OS -r $TARGET_ARCH
  - ./scripts/ci/build-installers.sh -o $HOST_OS -r $TARGET_ARCH

after_success:
  - cd dist
  - ls -lh
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh -O /tmp/upload.sh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "rewrite" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  # TODO: fix this dirty hack:
  - find -type f -iname '*.AppImage*'
  - bash -xc "find -type f -iname '*.AppImage*' -print0 | xargs -0 bash /tmp/upload.sh"

notifications:
  email: false
